import { columns, Payment } from "./columns"
import { DataTable } from "./data-table"

async function getData(): Promise<Payment[]> {
    return [
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "success",
            email: "m@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "pending",
            email: "m@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "success",
            email: "m@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "processing",
            email: "lisa@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "success",
            email: "m@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "failed",
            email: "john.doe@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "failed",
            email: "john.doe@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "success",
            email: "alice@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "failed",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "success",
            email: "alice@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "failed",
            email: "bob@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "processing",
            email: "lisa@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "processing",
            email: "sara@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "pending",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "processing",
            email: "sara@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "failed",
            email: "john.doe@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "success",
            email: "alice@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "failed",
            email: "bob@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "pending",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "processing",
            email: "sara@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "processing",
            email: "lisa@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "success",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "pending",
            email: "alice@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "processing",
            email: "john.doe@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "failed",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "success",
            email: "sara@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "success",
            email: "lisa@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "pending",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "failed",
            email: "alice@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "success",
            email: "john.doe@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "processing",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "pending",
            email: "sara@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "failed",
            email: "lisa@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "success",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "pending",
            email: "alice@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "processing",
            email: "john.doe@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "success",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "failed",
            email: "sara@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "pending",
            email: "lisa@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "pending",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "success",
            email: "alice@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "pending",
            email: "john.doe@example.com",
        },
        {
            id: "728ed52f",
            username: "Mohamed Khaled",
            amount: 100,
            status: "success",
            email: "m@example.com",
        },
        {
            id: "a92kd23d",
            username: "Sara Ali",
            amount: 250,
            status: "success",
            email: "sara@example.com",
        },
        {
            id: "e47nf02k",
            username: "Lisa Adams",
            amount: 60,
            status: "processing",
            email: "lisa@example.com",
        },
        {
            id: "d38me92j",
            username: "Bob Johnson",
            amount: 450,
            status: "failed",
            email: "bob@example.com",
        },
        {
            id: "c29dk67x",
            username: "Alice Smith",
            amount: 320,
            status: "pending",
            email: "alice@example.com",
        },
        {
            id: "b82lk88f",
            username: "John Doe",
            amount: 75,
            status: "failed",
            email: "john.doe@example.com",
        },
    ]
}

export default async function DemoPage() {
    const data = await getData()

    return (

        <div className='mb-8 px-4 py-2 bg-secondary rounded-md'>
            <h1 className='font-semibold mb-5'>All Payments</h1>
            <DataTable columns={columns} data={data} />
        </div>
    )
}